ALTER TABLE MULTA ADD pago_em2 timestamp;
CREATE SEQUENCE seq START WITH 1 INCREMENT BY 2 MINVALUE 0 MAXVALUE 100 CYCLE;
CREATE INDEX index_alu ON aluguel(inicio);
UPDATE usuario SET nome = 'Adrielly Nascimento da Silva' WHERE cpf = '999.999.999-99';
DELETE FROM desconto WHERE cpf = '111.111.111-11';
SELECT * FROM usuario WHERE cpf = '999.999.999-99';
SELECT * FROM multa WHERE valor BETWEEN 10 AND 100;
SELECT * FROM bicicleta WHERE ID_bicicleta IN (1,2,3,4,10);
SELECT * FROM usuario WHERE cpf LIKE '999.999.999-%';
SELECT * FROM multa WHERE pago_em IS NULL;
SELECT * FROM multa WHERE pago_em IS NOT NULL;
SELECT * from multa INNER JOIN usuario ON multa.cpf = usuario.cpf;
SELECT MAX(valor), MIN(valor), AVG(valor), COUNT(*) FROM multa;
SELECT * FROM usuario LEFT JOIN multa ON usuario.cpf = multa.cpf;
SELECT * FROM multa WHERE valor > (SELECT AVG(valor) FROM multa);
SELECT * FROM multa WHERE valor < ANY (SELECT valor FROM multa where valor>40);
SELECT * FROM multa ORDER BY valor DESC;
SELECT COUNT(*) FROM usuario_plano GROUP BY usuario_plano_id HAVING COUNT(*) < 100;
SELECT nome FROM usuario WHERE cpf LIKE '999.999%' UNION SELECT nome FROM usuario WHERE cpf LIKE '999.888%';
-- GRANT ALL ON multas TO user;
-- REVOKE ALL ON multas FROM user;
